server:
  port: 9003
spring:
  application:
    name: demo-gateway
  cloud:
    gateway:
      routes:
      - id: demo-consumer
        uri: ${test.uri} # uri以lb://开头（lb代表从注册中心获取服务），后面接的就是你需要转发到的服务名称
        predicates:
      - Path=/user/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/