server:
  port: 9002
spring:
  application:
    name: demo-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
feign:
  hystrix:
    enabled: true
#demo-server:
#  ribbon:
#    NFLoadBalanceRuleClassName: com.netfilx.loadbalancer.RandomRule